cmake_minimum_required(VERSION 3.10)
project("test" VERSION 0.1.0 LANGUAGES C)
set(BINARY ${PROJECT_NAME})
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)

add_compile_options(-Wall -Wextra -Werror -pedantic)
set(CMAKE_BUILD_TYPE Debug)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/../bin)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/../bin)
#find_package(Boost 1.71.0 REQUIRED)
#find_package(Eigen3 3.3 REQUIRED NO_MODULE)
#link_directories(${CMAKE_SOURCE_DIR}/lib)

file(GLOB SOURCES "src/*.c")
add_executable(${BINARY} ${SOURCES})
target_include_directories(${BINARY} PRIVATE include)
# target_link_libraries(${BINARY} PRIVATE libraryNames)
