#!/bin/sh

ffmpeg -y -f alsa -i default -acodec pcm_s16le -ac 1 -ar 44100 -t 5 -f wav ~/.cache/command.wav >/dev/null 2>&1
vosk-transcriber -m ~/Projects/models/speechToTxt/vosk-model-small-en-us-0.15 -i ~/.cache/command.wav -o ~/.cache/command.txt >/dev/null 2>&1

cat ~/.cache/command.txt

#try to find a way to keep the model loaded in memory so that it doesn't have to be loaded every time
