#!/bin/sh
set -e

check_sudo() 
{
    if [ "$(id -u)" -ne 0 ]; then
        echo "Run this script with sudo"
        exit 1
    fi
}
check_sudo

echo "Enter brightness value (typical: 35000): "
read brightness
echo "$brightness" > /sys/class/backlight/intel_backlight/brightness

