#!/bin/bash
{ while true; do sensors | awk 'BEGIN{a=0}($1 == "Core"){a+=$3} END{print a/4.0f}'; sleep 1; done } | ttyplot -t "cpu temp" -u C -m 100

# { while true; do awk '{ printf("%.1f\n", $1/1000) }' /sys/class/thermal/thermal_zone0/temp; sleep 1; done } | ttyplot -t "cpu temp" -u C
