#!/usr/bin/env bash

# no alacritty.toml? no script
[[ ! -f ~/.config/alacritty/alacritty.toml ]] && notify-send "alacritty.toml does not exist" && exit 0

# awk awk awk
opacity=$(awk -F'=' '/opacity/ {gsub(/[[:space:]]/, "", $2); print $2; exit}' ~/.config/alacritty/alacritty.toml)

case $opacity in
	1)
		toggle_opacity=0.1
		;;
	0.1)
		toggle_opacity=0.3
		;;
	0.3)
		toggle_opacity=0.5
		;;
	0.5)
		toggle_opacity=0.7
		;;
	0.7)
		toggle_opacity=0.9
		;;
	0.9)
		toggle_opacity=1
		;;
	*)
		toggle_opacity=0.5
		;;
esac
#doing it this way allows me to cycle through custom opacity values
#and makes it easier to add more values in the future

# replace
sed -i -- "s/opacity = $opacity/opacity = $toggle_opacity/" ~/.config/alacritty/alacritty.toml
